### PR TITLE
TIL: Building and contributing back to a Golang project (aka short-lived forks)

### PR DESCRIPTION
**Pull request by marvinpinto**

### CODE REVIEW

**Comment by moorereason** [comment]
Not sure where to have this conversation, so I'm coming here.  :smile:

There's a better way to work with forks in Go: use Git remotes. Assuming that you have Go setup and have forked the project in GitHub (in this case), do this:

``` shell
go get -u -v -t github.com/spf13/hugo
cd $GOPATH/src/github.com/spf13/hugo
git checkout -b new-amazing-patch
# do your edits...
go test ./...
git commit -a -v
# Here's the important stuff:
git remote add fork git@github.com:USERNAME/hugo.git
git push --set-upstream fork new-amazing-patch
```

### Why is this necessary?

The issue is that the `import` paths in the Go files reference `github.com/spf13/hugo`, even within Hugo itself!  So, you forking and changing files in `github.com/marvinpinto/hugo` get ignored during the build process because none of the Go files are importing your packages.

I used to use [govers](https://github.com/rogpeppe/govers) to rewrite import paths, but that was often problematic and annoying.  Git remotes is the best option.  It's all I ever use anymore for Go forks.

**Comment by marvinpinto** [comment]
Ahh, yes! Git remotes do indeed sound like a better solution, thank you for that!

Do you have any thoughts as to why the symlinking method I alluded to did not work? Conceptually it should have been the same result as using git remotes or cloning into a specific path in the filesystem (like in that TIL).

I was stumped :confused:

(btw updating that TIL feels like the right way to go. Were you interested in PRing that? "no" here is completely okay, too! :smile:)

**Comment by moorereason** [comment]
It seems like the symlink thing should have worked.  I'm surprised it didn't.

No, I don't want to rewrite your article. :smile: It should be updated, but I don't have time to do it.  I just wanted to make sure other Go newbies weren't lead down a bad path.  FWIW, I only learned about the Git remotes workflow two or three months ago.

**Comment by marvinpinto** [comment]
Sounds good! Thanks for letting me know :+1:

**Pull request merged**
